import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";

const mabryPro = localFont({
  src: "./fonts/MabryPro.woff",
  variable: "--font-mabry",
  weight: "400",
});
const inter = localFont({
  src: "./fonts/Inter.ttf",
  variable: "--font-inter",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${mabryPro.variable} ${inter.variable} antialiased px-4 md:px-16 px-50`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
